language: python
os:
  - linux

python:
  - "3.5"

services:
  - redis-server
  - postgresql

before_install:
  - createdb $(basename $PWD)
  - echo -e "SECRET_KEY = 'not so sectret!'\n" > ./_project_/settings_local.py

install:
  - pip install -r requirements.txt

script:
  - python manage.py migrate
  - python manage.py collectstatic
  - python manage.py check
  - pytest --cov-config .coveragerc --cov-report term-missing --cov . --selenium
  - prospector -s veryhigh .
